### ISSUE TITLE
Not an optimal solution

### ISSUE THREAD

**Issue by rjegaraj** [saiwaimaung/InterviewQuestionsPreparation#2]
Nice start on the rotating array, but your solution runs in O(n) time and O(n) space. The optimal solution is O(1) space and O(n) time.

**Comment by saiwaimaung** [comment]
Send a pull request

**Comment by saiwaimaung** [comment]
Space is cheap!

**Comment by rjegaraj** [comment]
No pull request, you should figure out how to do it :)

Space IS cheap, but that won't fly for an interview

**Comment by rjegaraj** [comment]
I'm closing this as for a day-to-day use, your algo is fine. But be mindful that a more optimal solution exists going forward
